name: Deploy to Amazon ECS

on:
  push:
    branches:
      - in-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: "my-cluster"
      SERVICE_NAME: "cloud-service"
      REPO_NAME: "cloud"

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Step 6: Create ECR Repository if it doesn't exist
      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names "${{ env.REPO_NAME }}" || \
          aws ecr create-repository --repository-name "${{ env.REPO_NAME }}"

      # Step 7: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:latest"
          docker build -t $IMAGE_URI .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Step 8: Push Docker image to Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.IMAGE_URI }}

      # Step 9: Register ECS Task Definition
      - name: Register ECS Task Definition
        run: |
          cat <<EOF > ecs-task-definition.json
          {
            "family": "${{ env.SERVICE_NAME }}",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "cloud-container",
                "image": "${{ env.IMAGE_URI }}",
                "memory": 256,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 8080,
                    "hostPort": 8080
                  }
                ],
                "environment": [
                  {
                    "name": "SPRING_DATASOURCE_URL",
                    "value": "jdbc:postgresql://postgres-container:5432/cloud_db"
                  },
                  {
                    "name": "SPRING_DATASOURCE_USERNAME",
                    "value": "user"
                  },
                  {
                    "name": "SPRING_DATASOURCE_PASSWORD",
                    "value": "${{ secrets.POSTGRES_PASSWORD }}"
                  }
                ]
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "${{ secrets.ECS_EXECUTION_ROLE_ARN }}",
            "taskRoleArn": "${{ secrets.ECS_TASK_ROLE_ARN }}"
          }
          EOF

          aws ecs register-task-definition --cli-input-json file://ecs-task-definition.json

      # Step 10: Create VPC, Subnet, and Security Group
      # These steps can be separated out as a one-time setup process for stability.

      # Step 11: Create ECS Cluster if not exists
      - name: Create ECS Cluster if not exists
        run: |
          CLUSTER_OUTPUT=$(aws ecs describe-clusters --clusters "${{ env.CLUSTER_NAME }}" --output json 2>/dev/null)
          if [ "$(echo $CLUSTER_OUTPUT | jq -r '.clusters | length')" -eq 0 ]; then
            aws ecs create-cluster --cluster-name "${{ env.CLUSTER_NAME }}" --output json
          fi

      # Step 12: Check if ECS Service Exists and Create if Necessary
      - name: Check and Create ECS Service if Needed
        run: |
          SERVICE_OUTPUT=$(aws ecs describe-services --cluster "${{ env.CLUSTER_NAME }}" --services "${{ env.SERVICE_NAME }}" --output json 2>/dev/null)
          if [ "$(echo $SERVICE_OUTPUT | jq -r '.services | length')" -eq 0 ]; then
            aws ecs create-service --cluster "${{ env.CLUSTER_NAME }}" --service-name "${{ env.SERVICE_NAME }}" --task-definition "${{ env.SERVICE_NAME }}" --desired-count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[${{ env.SUBNET_ID }}],securityGroups=[${{ env.SECURITY_GROUP_ID }}],assignPublicIp='ENABLED'}"
          fi

      # Step 13: Update ECS Service
      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster "${{ env.CLUSTER_NAME }}" --service "${{ env.SERVICE_NAME }}" --task-definition "${{ env.SERVICE_NAME }}" --force-new-deployment || echo "Failed to update service."
